### ISSUE TITLE
skippy-xd problem

### ISSUE THREAD

**Issue by mrneilypops** [2ion/dwm#1]
Hi,
I am trying to install your dwm fork on Void linux but I get an error that skippy-xd is not found.
Any help much appreciated.

**Comment by 2ion** [comment]
* It's just a tool bound to Mod4+Backspace which provides an exposé-like view on windows. It's linked in the readme. On your distro, a package may exist or not: https://github.com/2ion/dwm#skippy-xd
 * It just to be integrated with the build system but that it's not true anymore. Make sure you are using the branch tpx240.

**Comment by 2ion** [comment]
@mrneilypops I do not maintain this dwm fork anymore since I've since switched to KDE/kwm, so I'll close this issue.
